export enum ScheduleEnum {
    TITLE = 'Send Later',
    USERNAME_ALIAS = 'Sendlater',
    VIEW_ID = 'schedule',
    VIEW_LIST = 'View list',
    VIEW_LIST_ID = 'schedule-list',
    TIME_ACTION_ID = 'time',
    TIME_LABEL = 'When do you want the message to be sent?',
    TIME_PLACEHOLDER = '10 minutes, 18:15, 2022-01-01T00:00:00',
    MESSAGE_ACTION_ID = 'message',
    MESSAGE_LABEL = 'What is your message?',
    CANCEL = 'Cancel',
    CANCELLED = 'Cancelled.',
    CANCEL_ID = 'cancel',
    NO_TASKS_MESSAGE = 'You have no scheduled messages.',
    MESSAGE_SCHEDULED = 'Your message has been scheduled.',
}
